### ISSUE TITLE
Training scripts for cifar10

### ISSUE THREAD

**Issue by lukk47** [ML-GSAI/DPT#1]
Hi, I am interested in the training scripts for cifar10 related experiments. Are they available? Thanks.

**Comment by yyyouy** [comment]
Thank you very much for your interest in our work, we will update our code in August. Thank you.

**Comment by yyyouy** [comment]
> Hi, I am interested in the training scripts for cifar10 related experiments. Are they available? Thanks.

Hi, sorry for your waiting, the training script for the CIFAR-10 dataset will be available soon (before this weekend).

**Comment by yyyouy** [comment]
We have added the training script for the CIFAR-10. if you have any questions, welcome to email me.
