### ISSUE TITLE
CIFAR-10 training script

### ISSUE THREAD

**Issue by BotaiYuan** [ML-GSAI/DPT#2]
Hi，this is an excellent work. I am wondering whether the training script for CIFAR-10 dataset is available. Thanks!

**Comment by yyyouy** [comment]
Hi, thanks for your feedback, the training script for the CIFAR-10 dataset will be available soon (before this weekend).

**Comment by yyyouy** [comment]
we have added the training script for the CIFAR-10. if you have any question, welcome to email me.
