### ISSUE TITLE
about "TorchSSL\ save_module" can't find

### ISSUE THREAD

**Issue by holydick99** [ML-GSAI/DPT#4]
hello, when i run the code in the first stage(Training the Classifier and Generating Pseudo-Labels) I can't find where is the "TorchSSL\ save_module" path, but there is a config file maybe own the same function?

**Comment by holydick99** [comment]
and also after i run the (python freematch.py --c config/freematch_cifar10_40_1.yaml), there are no models be saved with some userwarning, how should i deal with it

**Comment by yyyouy** [comment]
> hello, when i run the code in the first stage(Training the Classifier and Generating Pseudo-Labels) I can't find where is the "TorchSSL\ save_module" path, but there is a config file maybe own the same function?

can you show some image to show your wrong?

**Comment by holydick99** [comment]
> > hello, when i run the code in the first stage(Training the Classifier and Generating Pseudo-Labels) I can't find where is the "TorchSSL\ save_module" path, but there is a config file maybe own the same function?
> 
> can you show some image to show your wrong?

after i run the (python freematch.py --c config/freematch_cifar10_40_1.yaml), there are no models be saved with some userwarning, how should i deal with it？
![E$UF{X)L)3G%S$S$UQ3{`O8](https://github.com/user-attachments/assets/5af0927a-8f05-41b4-8133-f2fb1d6102ee)
![E$UF{X)L)3G%S$S$UQ3{`O8](https://github.com/user-attachments/assets/df0dbe0f-9ed3-4b83-8ee0-96b638a68345)

**Comment by yyyouy** [comment]
It seems that you might not have started up properly. Perhaps you could give it a try on an Ubuntu system and see if it runs, or check out the documentation for the TorchSSL library, where there's a more detailed guide on how to get it running.

**Comment by yyyouy** [comment]
I haven't tried it on a Windows system. Therefore, I'm also unsure of the specific reason.

**Comment by yyyouy** [comment]
> > > hello, when i run the code in the first stage(Training the Classifier and Generating Pseudo-Labels) I can't find where is the "TorchSSL\ save_module" path, but there is a config file maybe own the same function?
> > 
> > 
> > can you show some image to show your wrong?
> 
> after i run the (python freematch.py --c config/freematch_cifar10_40_1.yaml), there are no models be saved with some userwarning, how should i deal with it？ ![E$UF{X)L)3G%S$S$UQ3{O8](https://github.com/user-attachments/assets/5af0927a-8f05-41b4-8133-f2fb1d6102ee) ![E$UF{X)L)3G%S$S$UQ3{O8](https://private-user-images.githubusercontent.com/146045710/349509920-df0dbe0f-9ed3-4b83-8ee0-96b638a68345.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODMxNDYsIm5iZiI6MTcyMTI4Mjg0NiwicGF0aCI6Ii8xNDYwNDU3MTAvMzQ5NTA5OTIwLWRmMGRiZTBmLTllZDMtNGI4My04ZWUwLTk2YjYzOGE2ODM0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwNjA3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2U0ZWMxZWU2Y2QxMmE3OWI4ODY4MzI2ODkzYjNkY2YyMDZhNDI2ZTdmMDc1OTdiNTcwZTg2ZDg5ZjBiNWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CJDPoYJ0jkZ59rRa6NmScJXnGOJWieN4JMqD7TvAkUE)

hello, have you solved your problem now?

**Comment by holydick99** [comment]
> > > > hello, when i run the code in the first stage(Training the Classifier and Generating Pseudo-Labels) I can't find where is the "TorchSSL\ save_module" path, but there is a config file maybe own the same function?
> > > 
> > > 
> > > can you show some image to show your wrong?
> > 
> > 
> > after i run the (python freematch.py --c config/freematch_cifar10_40_1.yaml), there are no models be saved with some userwarning, how should i deal with it？ ![E$UF{X)L)3G%S$S$UQ3{O8](https://private-user-images.githubusercontent.com/146045710/349509835-5af0927a-8f05-41b4-8133-f2fb1d6102ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzODU4NTgsIm5iZiI6MTcyMTM4NTU1OCwicGF0aCI6Ii8xNDYwNDU3MTAvMzQ5NTA5ODM1LTVhZjA5MjdhLThmMDUtNDFiNC04MTMzLWYyZmIxZDYxMDJlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxMDM5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjhhNzA2ZTI3ZDFhNDQzM2I2ZjMyNmRhYjU4N2RlOGEzNzViOGJhMjQwMDliYTcyYTFjZGMzMGE3ODRhODQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PJfvpbNdcwlQk8oEwwrj26mi8drg99pkVTqL7GpUmrc) ![E$UF{X)L)3G%S$S$UQ3{O8](https://private-user-images.githubusercontent.com/146045710/349509920-df0dbe0f-9ed3-4b83-8ee0-96b638a68345.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODMxNDYsIm5iZiI6MTcyMTI4Mjg0NiwicGF0aCI6Ii8xNDYwNDU3MTAvMzQ5NTA5OTIwLWRmMGRiZTBmLTllZDMtNGI4My04ZWUwLTk2YjYzOGE2ODM0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwNjA3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2U0ZWMxZWU2Y2QxMmE3OWI4ODY4MzI2ODkzYjNkY2YyMDZhNDI2ZTdmMDc1OTdiNTcwZTg2ZDg5ZjBiNWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CJDPoYJ0jkZ59rRa6NmScJXnGOJWieN4JMqD7TvAkUE)
> 
> hello, have you solved your problem now?

maybe solved it, the reason is some libs are based on linux they cannot run on windows system and due to my laptop only have one Graphics the "nccl" must change to "goo". unfortunately my memory is not enough to support this project hahaha
