### ISSUE TITLE
the last step

### ISSUE THREAD

**Issue by holydick99** [ML-GSAI/DPT#5]
the last step it look same as the first step but when i input the command line it always runtime error.
![@K5_XZ38F}S_U9~I_BY %%X](https://github.com/user-attachments/assets/eb94ec97-4251-4ed4-84b3-81c861990172)

**Comment by yyyouy** [comment]
try this: https://github.com/THUDM/ChatGLM-6B/pull/1173/files
maybe this is because the problem of version.

**Comment by yyyouy** [comment]
thank you for your attention. try this: https://github.com/THUDM/ChatGLM-6B/pull/1173/files
maybe this is because of the problem of version.

**Comment by holydick99** [comment]
sorry about that im a green-hand of this area, so this solution means use these code to replace the original code?

**Comment by yyyouy** [comment]
HH, don't feel sorry, I know issues with the environment can be frustrating. What I mean is, try adding the code included to see if it helps. It might be due to torchrun. Try launching with torchrun and also add the code from the link at the beginning of your training script.

**Comment by holydick99** [comment]
![$Y0S}80(LIB441R2B5LL 6L](https://github.com/user-attachments/assets/1ab6d925-294d-4ca5-8948-60d53b51957e)
so this specific is change this code?

**Comment by yyyouy** [comment]
yes, you can have a try.

**Comment by holydick99** [comment]
> HH, don't feel sorry, I know issues with the environment can be frustrating. What I mean is, try adding the code included to see if it helps. It might be due to torchrun. Try launching with torchrun and also add the code from the link at the beginning of your training script.

really thank u, the right way is replace that code to (torch.distributed.init_process_group), then it can run normally

**Comment by yyyouy** [comment]
> > HH, don't feel sorry, I know issues with the environment can be frustrating. What I mean is, try adding the code included to see if it helps. It might be due to torchrun. Try launching with torchrun and also add the code from the link at the beginning of your training script.
> 
> really thank u, the right way is replace that code to (torch.distributed.init_process_group), then it can run normally

very glad to hear this method can help you.
